(in-package :snmp)

#+lispworks
(eval-when (:load-toplevel :execute)
  (define-object-id "sysContact" (o) lispworks:*phone-home*))

#+lispworks
(defun update-mib ()
  (let ((mib.lisp-expr '()))
    (dolist (i *mib-list*)
      (format t "; Compiling ~A~%" i)
      (compile-asn.1 i :to (lisp-file i))
      (let ((depends (with-open-file (s (expr-file i) :direction :input)
                       (read s)))
            (name (string-downcase (pathname-name (lisp-file i)))))
        (push (if depends
                  `(:file ,name :depends-on ,depends)
                `(:file ,name))
              mib.lisp-expr)))
    (with-open-file (s *mib-list-file*
                       :direction :output
                       :if-exists :supersede)
      (format s ";;;; -*- Mode: Lisp -*-~%;;;; Auto-generated by SNMP:UPDATE-MIB.LISP~%")
      (pprint (setf mib.lisp-expr (nreverse mib.lisp-expr)) s)
      (format s "~%"))
    (load #p"SNMP:SNMP.ASD")
    (pprint mib.lisp-expr)))
