;;;; -*- Mode: Lisp -*-
;;;; Generated by #p"SNMP:UPDATE-MIB.LISP"

(IN-PACKAGE :ASN.1)

(EVAL-WHEN (:LOAD-TOPLEVEL :EXECUTE)
  (MAPCAR #'(LAMBDA (X)
              (SETF (GETHASH (CAR X) *MIB-MODULE-DEPENDENCY*) (CDR X)))
          '((HOST-RESOURCES-MIB
             |SNMPv2-SMI|
             |SNMPv2-TC|
             |SNMPv2-CONF|
             IF-MIB)
            (IF-MIB
             |SNMPv2-SMI|
             |SNMPv2-TC|
             |SNMPv2-CONF|
             |SNMPv2-MIB|
             |IANAifType-MIB|)
            (|IANAifType-MIB| |SNMPv2-SMI| |SNMPv2-TC|)
            (|SNMPv2-MIB| |SNMPv2-SMI| |SNMPv2-TC| |SNMPv2-CONF|)
            (|SNMPv2-CONF| |SNMPv2-SMI|)
            (|SNMPv2-TM| |SNMPv2-SMI| |SNMPv2-TC|)
            (|SNMPv2-TC| |SNMPv2-SMI|))))
