;;;; -*- Mode: Lisp -*-
;;;; Generated by #p"SNMP:UPDATE-MIB.LISP"

(in-package :asn.1)

(eval-when (:load-toplevel :execute)
  (mapcar #'(lambda (x)
              (setf (gethash (car x) *mib-module-dependency*) (cdr x)))
          '((|IANAifType-MIB| |SNMPv2-SMI| |SNMPv2-TC|)
            (|SNMPv2-MIB| |SNMPv2-SMI| |SNMPv2-TC| |SNMPv2-CONF|)
            (|SNMPv2-CONF| |SNMPv2-SMI|)
            (|SNMPv2-TM| |SNMPv2-SMI| |SNMPv2-TC|)
            (|SNMPv2-TC| |SNMPv2-SMI|))))
