(in-package :snmp)

(def-scalar-variable "lispImplementationType" (agent)
  (lisp-implementation-type))
(def-scalar-variable "lispImplementationVersion" (agent)
  (lisp-implementation-version))
(def-scalar-variable "lispMachineInstance" (agent)
  (machine-instance))
(def-scalar-variable "lispMachineType" (agent)
  (machine-type))
(def-scalar-variable "lispMachineVersion" (agent)
  (machine-version))
(def-scalar-variable "lispSoftwareType" (agent)
  (software-type))
(def-scalar-variable "lispSoftwareVersion" (agent)
  (software-version))
